/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OnboardingLinkRouteImport } from './routes/onboarding/link'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardWebGuidesRouteImport } from './routes/dashboard/web/guides'
import { Route as DashboardTelegramGroupsRouteImport } from './routes/dashboard/telegram/groups'
import { Route as DashboardTelegramGrantsRouteImport } from './routes/dashboard/telegram/grants'
import { Route as DashboardAzureMembersRouteImport } from './routes/dashboard/azure/members'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardTelegramUsersIndexRouteImport } from './routes/dashboard/telegram/users/index'
import { Route as DashboardTelegramUsersUserIdRouteImport } from './routes/dashboard/telegram/users/$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OnboardingLinkRoute = OnboardingLinkRouteImport.update({
  id: '/onboarding/link',
  path: '/onboarding/link',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebGuidesRoute = DashboardWebGuidesRouteImport.update({
  id: '/web/guides',
  path: '/web/guides',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTelegramGroupsRoute = DashboardTelegramGroupsRouteImport.update({
  id: '/telegram/groups',
  path: '/telegram/groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTelegramGrantsRoute = DashboardTelegramGrantsRouteImport.update({
  id: '/telegram/grants',
  path: '/telegram/grants',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAzureMembersRoute = DashboardAzureMembersRouteImport.update({
  id: '/azure/members',
  path: '/azure/members',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTelegramUsersIndexRoute =
  DashboardTelegramUsersIndexRouteImport.update({
    id: '/telegram/users/',
    path: '/telegram/users/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTelegramUsersUserIdRoute =
  DashboardTelegramUsersUserIdRouteImport.update({
    id: '/telegram/users/$userId',
    path: '/telegram/users/$userId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/onboarding/link': typeof OnboardingLinkRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/azure/members': typeof DashboardAzureMembersRoute
  '/dashboard/telegram/grants': typeof DashboardTelegramGrantsRoute
  '/dashboard/telegram/groups': typeof DashboardTelegramGroupsRoute
  '/dashboard/web/guides': typeof DashboardWebGuidesRoute
  '/dashboard/telegram/users/$userId': typeof DashboardTelegramUsersUserIdRoute
  '/dashboard/telegram/users/': typeof DashboardTelegramUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/onboarding/link': typeof OnboardingLinkRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/azure/members': typeof DashboardAzureMembersRoute
  '/dashboard/telegram/grants': typeof DashboardTelegramGrantsRoute
  '/dashboard/telegram/groups': typeof DashboardTelegramGroupsRoute
  '/dashboard/web/guides': typeof DashboardWebGuidesRoute
  '/dashboard/telegram/users/$userId': typeof DashboardTelegramUsersUserIdRoute
  '/dashboard/telegram/users': typeof DashboardTelegramUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/onboarding/link': typeof OnboardingLinkRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/azure/members': typeof DashboardAzureMembersRoute
  '/dashboard/telegram/grants': typeof DashboardTelegramGrantsRoute
  '/dashboard/telegram/groups': typeof DashboardTelegramGroupsRoute
  '/dashboard/web/guides': typeof DashboardWebGuidesRoute
  '/dashboard/telegram/users/$userId': typeof DashboardTelegramUsersUserIdRoute
  '/dashboard/telegram/users/': typeof DashboardTelegramUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/account'
    | '/onboarding/link'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/azure/members'
    | '/dashboard/telegram/grants'
    | '/dashboard/telegram/groups'
    | '/dashboard/web/guides'
    | '/dashboard/telegram/users/$userId'
    | '/dashboard/telegram/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/account'
    | '/onboarding/link'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/azure/members'
    | '/dashboard/telegram/grants'
    | '/dashboard/telegram/groups'
    | '/dashboard/web/guides'
    | '/dashboard/telegram/users/$userId'
    | '/dashboard/telegram/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/account'
    | '/onboarding/link'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/azure/members'
    | '/dashboard/telegram/grants'
    | '/dashboard/telegram/groups'
    | '/dashboard/web/guides'
    | '/dashboard/telegram/users/$userId'
    | '/dashboard/telegram/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingLinkRoute: typeof OnboardingLinkRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/onboarding/link': {
      id: '/onboarding/link'
      path: '/onboarding/link'
      fullPath: '/onboarding/link'
      preLoaderRoute: typeof OnboardingLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/web/guides': {
      id: '/dashboard/web/guides'
      path: '/web/guides'
      fullPath: '/dashboard/web/guides'
      preLoaderRoute: typeof DashboardWebGuidesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/telegram/groups': {
      id: '/dashboard/telegram/groups'
      path: '/telegram/groups'
      fullPath: '/dashboard/telegram/groups'
      preLoaderRoute: typeof DashboardTelegramGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/telegram/grants': {
      id: '/dashboard/telegram/grants'
      path: '/telegram/grants'
      fullPath: '/dashboard/telegram/grants'
      preLoaderRoute: typeof DashboardTelegramGrantsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/azure/members': {
      id: '/dashboard/azure/members'
      path: '/azure/members'
      fullPath: '/dashboard/azure/members'
      preLoaderRoute: typeof DashboardAzureMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/telegram/users/': {
      id: '/dashboard/telegram/users/'
      path: '/telegram/users'
      fullPath: '/dashboard/telegram/users/'
      preLoaderRoute: typeof DashboardTelegramUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/telegram/users/$userId': {
      id: '/dashboard/telegram/users/$userId'
      path: '/telegram/users/$userId'
      fullPath: '/dashboard/telegram/users/$userId'
      preLoaderRoute: typeof DashboardTelegramUsersUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAzureMembersRoute: typeof DashboardAzureMembersRoute
  DashboardTelegramGrantsRoute: typeof DashboardTelegramGrantsRoute
  DashboardTelegramGroupsRoute: typeof DashboardTelegramGroupsRoute
  DashboardWebGuidesRoute: typeof DashboardWebGuidesRoute
  DashboardTelegramUsersUserIdRoute: typeof DashboardTelegramUsersUserIdRoute
  DashboardTelegramUsersIndexRoute: typeof DashboardTelegramUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAzureMembersRoute: DashboardAzureMembersRoute,
  DashboardTelegramGrantsRoute: DashboardTelegramGrantsRoute,
  DashboardTelegramGroupsRoute: DashboardTelegramGroupsRoute,
  DashboardWebGuidesRoute: DashboardWebGuidesRoute,
  DashboardTelegramUsersUserIdRoute: DashboardTelegramUsersUserIdRoute,
  DashboardTelegramUsersIndexRoute: DashboardTelegramUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingLinkRoute: OnboardingLinkRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
