/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWebRouteImport } from './routes/dashboard/web'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardWhatsappGroupsRouteImport } from './routes/dashboard/whatsapp/groups'
import { Route as DashboardWebProjectsRouteImport } from './routes/dashboard/web/projects'
import { Route as DashboardWebGuidesRouteImport } from './routes/dashboard/web/guides'
import { Route as DashboardWebGroupLabelsRouteImport } from './routes/dashboard/web/group-labels'
import { Route as DashboardWebFaqsRouteImport } from './routes/dashboard/web/faqs'
import { Route as DashboardWebAssociationsRouteImport } from './routes/dashboard/web/associations'
import { Route as DashboardTelegramGroupsRouteImport } from './routes/dashboard/telegram/groups'
import { Route as DashboardTelegramGrantsRouteImport } from './routes/dashboard/telegram/grants'
import { Route as DashboardReportsResolvedRouteImport } from './routes/dashboard/reports/resolved'
import { Route as DashboardReportsGroupLinksRouteImport } from './routes/dashboard/reports/group-links'
import { Route as DashboardAzureMembersRouteImport } from './routes/dashboard/azure/members'
import { Route as DashboardWebGroupsByLabelIndexRouteImport } from './routes/dashboard/web/groups-by-label/index'
import { Route as DashboardTelegramUsersIndexRouteImport } from './routes/dashboard/telegram/users/index'
import { Route as DashboardWebTagsTagRouteImport } from './routes/dashboard/web/tags/$tag'
import { Route as DashboardWebGroupsByLabelSplatRouteImport } from './routes/dashboard/web/groups-by-label/$'
import { Route as DashboardTelegramUsersUserIdRouteImport } from './routes/dashboard/telegram/users/$userId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebRoute = DashboardWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWhatsappGroupsRoute = DashboardWhatsappGroupsRouteImport.update({
  id: '/whatsapp/groups',
  path: '/whatsapp/groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebProjectsRoute = DashboardWebProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardWebRoute,
} as any)
const DashboardWebGuidesRoute = DashboardWebGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => DashboardWebRoute,
} as any)
const DashboardWebGroupLabelsRoute = DashboardWebGroupLabelsRouteImport.update({
  id: '/group-labels',
  path: '/group-labels',
  getParentRoute: () => DashboardWebRoute,
} as any)
const DashboardWebFaqsRoute = DashboardWebFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => DashboardWebRoute,
} as any)
const DashboardWebAssociationsRoute =
  DashboardWebAssociationsRouteImport.update({
    id: '/associations',
    path: '/associations',
    getParentRoute: () => DashboardWebRoute,
  } as any)
const DashboardTelegramGroupsRoute = DashboardTelegramGroupsRouteImport.update({
  id: '/telegram/groups',
  path: '/telegram/groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTelegramGrantsRoute = DashboardTelegramGrantsRouteImport.update({
  id: '/telegram/grants',
  path: '/telegram/grants',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsResolvedRoute =
  DashboardReportsResolvedRouteImport.update({
    id: '/reports/resolved',
    path: '/reports/resolved',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsGroupLinksRoute =
  DashboardReportsGroupLinksRouteImport.update({
    id: '/reports/group-links',
    path: '/reports/group-links',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAzureMembersRoute = DashboardAzureMembersRouteImport.update({
  id: '/azure/members',
  path: '/azure/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebGroupsByLabelIndexRoute =
  DashboardWebGroupsByLabelIndexRouteImport.update({
    id: '/groups-by-label/',
    path: '/groups-by-label/',
    getParentRoute: () => DashboardWebRoute,
  } as any)
const DashboardTelegramUsersIndexRoute =
  DashboardTelegramUsersIndexRouteImport.update({
    id: '/telegram/users/',
    path: '/telegram/users/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWebTagsTagRoute = DashboardWebTagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => DashboardWebRoute,
} as any)
const DashboardWebGroupsByLabelSplatRoute =
  DashboardWebGroupsByLabelSplatRouteImport.update({
    id: '/groups-by-label/$',
    path: '/groups-by-label/$',
    getParentRoute: () => DashboardWebRoute,
  } as any)
const DashboardTelegramUsersUserIdRoute =
  DashboardTelegramUsersUserIdRouteImport.update({
    id: '/telegram/users/$userId',
    path: '/telegram/users/$userId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/web': typeof DashboardWebRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/azure/members': typeof DashboardAzureMembersRoute
  '/dashboard/reports/group-links': typeof DashboardReportsGroupLinksRoute
  '/dashboard/reports/resolved': typeof DashboardReportsResolvedRoute
  '/dashboard/telegram/grants': typeof DashboardTelegramGrantsRoute
  '/dashboard/telegram/groups': typeof DashboardTelegramGroupsRoute
  '/dashboard/web/associations': typeof DashboardWebAssociationsRoute
  '/dashboard/web/faqs': typeof DashboardWebFaqsRoute
  '/dashboard/web/group-labels': typeof DashboardWebGroupLabelsRoute
  '/dashboard/web/guides': typeof DashboardWebGuidesRoute
  '/dashboard/web/projects': typeof DashboardWebProjectsRoute
  '/dashboard/whatsapp/groups': typeof DashboardWhatsappGroupsRoute
  '/dashboard/telegram/users/$userId': typeof DashboardTelegramUsersUserIdRoute
  '/dashboard/web/groups-by-label/$': typeof DashboardWebGroupsByLabelSplatRoute
  '/dashboard/web/tags/$tag': typeof DashboardWebTagsTagRoute
  '/dashboard/telegram/users/': typeof DashboardTelegramUsersIndexRoute
  '/dashboard/web/groups-by-label/': typeof DashboardWebGroupsByLabelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/web': typeof DashboardWebRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/azure/members': typeof DashboardAzureMembersRoute
  '/dashboard/reports/group-links': typeof DashboardReportsGroupLinksRoute
  '/dashboard/reports/resolved': typeof DashboardReportsResolvedRoute
  '/dashboard/telegram/grants': typeof DashboardTelegramGrantsRoute
  '/dashboard/telegram/groups': typeof DashboardTelegramGroupsRoute
  '/dashboard/web/associations': typeof DashboardWebAssociationsRoute
  '/dashboard/web/faqs': typeof DashboardWebFaqsRoute
  '/dashboard/web/group-labels': typeof DashboardWebGroupLabelsRoute
  '/dashboard/web/guides': typeof DashboardWebGuidesRoute
  '/dashboard/web/projects': typeof DashboardWebProjectsRoute
  '/dashboard/whatsapp/groups': typeof DashboardWhatsappGroupsRoute
  '/dashboard/telegram/users/$userId': typeof DashboardTelegramUsersUserIdRoute
  '/dashboard/web/groups-by-label/$': typeof DashboardWebGroupsByLabelSplatRoute
  '/dashboard/web/tags/$tag': typeof DashboardWebTagsTagRoute
  '/dashboard/telegram/users': typeof DashboardTelegramUsersIndexRoute
  '/dashboard/web/groups-by-label': typeof DashboardWebGroupsByLabelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/web': typeof DashboardWebRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/azure/members': typeof DashboardAzureMembersRoute
  '/dashboard/reports/group-links': typeof DashboardReportsGroupLinksRoute
  '/dashboard/reports/resolved': typeof DashboardReportsResolvedRoute
  '/dashboard/telegram/grants': typeof DashboardTelegramGrantsRoute
  '/dashboard/telegram/groups': typeof DashboardTelegramGroupsRoute
  '/dashboard/web/associations': typeof DashboardWebAssociationsRoute
  '/dashboard/web/faqs': typeof DashboardWebFaqsRoute
  '/dashboard/web/group-labels': typeof DashboardWebGroupLabelsRoute
  '/dashboard/web/guides': typeof DashboardWebGuidesRoute
  '/dashboard/web/projects': typeof DashboardWebProjectsRoute
  '/dashboard/whatsapp/groups': typeof DashboardWhatsappGroupsRoute
  '/dashboard/telegram/users/$userId': typeof DashboardTelegramUsersUserIdRoute
  '/dashboard/web/groups-by-label/$': typeof DashboardWebGroupsByLabelSplatRoute
  '/dashboard/web/tags/$tag': typeof DashboardWebTagsTagRoute
  '/dashboard/telegram/users/': typeof DashboardTelegramUsersIndexRoute
  '/dashboard/web/groups-by-label/': typeof DashboardWebGroupsByLabelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/unauthorized'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/dashboard/account'
    | '/dashboard/web'
    | '/dashboard/'
    | '/dashboard/azure/members'
    | '/dashboard/reports/group-links'
    | '/dashboard/reports/resolved'
    | '/dashboard/telegram/grants'
    | '/dashboard/telegram/groups'
    | '/dashboard/web/associations'
    | '/dashboard/web/faqs'
    | '/dashboard/web/group-labels'
    | '/dashboard/web/guides'
    | '/dashboard/web/projects'
    | '/dashboard/whatsapp/groups'
    | '/dashboard/telegram/users/$userId'
    | '/dashboard/web/groups-by-label/$'
    | '/dashboard/web/tags/$tag'
    | '/dashboard/telegram/users/'
    | '/dashboard/web/groups-by-label/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/dashboard/account'
    | '/dashboard/web'
    | '/dashboard'
    | '/dashboard/azure/members'
    | '/dashboard/reports/group-links'
    | '/dashboard/reports/resolved'
    | '/dashboard/telegram/grants'
    | '/dashboard/telegram/groups'
    | '/dashboard/web/associations'
    | '/dashboard/web/faqs'
    | '/dashboard/web/group-labels'
    | '/dashboard/web/guides'
    | '/dashboard/web/projects'
    | '/dashboard/whatsapp/groups'
    | '/dashboard/telegram/users/$userId'
    | '/dashboard/web/groups-by-label/$'
    | '/dashboard/web/tags/$tag'
    | '/dashboard/telegram/users'
    | '/dashboard/web/groups-by-label'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/unauthorized'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/dashboard/account'
    | '/dashboard/web'
    | '/dashboard/'
    | '/dashboard/azure/members'
    | '/dashboard/reports/group-links'
    | '/dashboard/reports/resolved'
    | '/dashboard/telegram/grants'
    | '/dashboard/telegram/groups'
    | '/dashboard/web/associations'
    | '/dashboard/web/faqs'
    | '/dashboard/web/group-labels'
    | '/dashboard/web/guides'
    | '/dashboard/web/projects'
    | '/dashboard/whatsapp/groups'
    | '/dashboard/telegram/users/$userId'
    | '/dashboard/web/groups-by-label/$'
    | '/dashboard/web/tags/$tag'
    | '/dashboard/telegram/users/'
    | '/dashboard/web/groups-by-label/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/web': {
      id: '/dashboard/web'
      path: '/web'
      fullPath: '/dashboard/web'
      preLoaderRoute: typeof DashboardWebRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/whatsapp/groups': {
      id: '/dashboard/whatsapp/groups'
      path: '/whatsapp/groups'
      fullPath: '/dashboard/whatsapp/groups'
      preLoaderRoute: typeof DashboardWhatsappGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/web/projects': {
      id: '/dashboard/web/projects'
      path: '/projects'
      fullPath: '/dashboard/web/projects'
      preLoaderRoute: typeof DashboardWebProjectsRouteImport
      parentRoute: typeof DashboardWebRoute
    }
    '/dashboard/web/guides': {
      id: '/dashboard/web/guides'
      path: '/guides'
      fullPath: '/dashboard/web/guides'
      preLoaderRoute: typeof DashboardWebGuidesRouteImport
      parentRoute: typeof DashboardWebRoute
    }
    '/dashboard/web/group-labels': {
      id: '/dashboard/web/group-labels'
      path: '/group-labels'
      fullPath: '/dashboard/web/group-labels'
      preLoaderRoute: typeof DashboardWebGroupLabelsRouteImport
      parentRoute: typeof DashboardWebRoute
    }
    '/dashboard/web/faqs': {
      id: '/dashboard/web/faqs'
      path: '/faqs'
      fullPath: '/dashboard/web/faqs'
      preLoaderRoute: typeof DashboardWebFaqsRouteImport
      parentRoute: typeof DashboardWebRoute
    }
    '/dashboard/web/associations': {
      id: '/dashboard/web/associations'
      path: '/associations'
      fullPath: '/dashboard/web/associations'
      preLoaderRoute: typeof DashboardWebAssociationsRouteImport
      parentRoute: typeof DashboardWebRoute
    }
    '/dashboard/telegram/groups': {
      id: '/dashboard/telegram/groups'
      path: '/telegram/groups'
      fullPath: '/dashboard/telegram/groups'
      preLoaderRoute: typeof DashboardTelegramGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/telegram/grants': {
      id: '/dashboard/telegram/grants'
      path: '/telegram/grants'
      fullPath: '/dashboard/telegram/grants'
      preLoaderRoute: typeof DashboardTelegramGrantsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/resolved': {
      id: '/dashboard/reports/resolved'
      path: '/reports/resolved'
      fullPath: '/dashboard/reports/resolved'
      preLoaderRoute: typeof DashboardReportsResolvedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/group-links': {
      id: '/dashboard/reports/group-links'
      path: '/reports/group-links'
      fullPath: '/dashboard/reports/group-links'
      preLoaderRoute: typeof DashboardReportsGroupLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/azure/members': {
      id: '/dashboard/azure/members'
      path: '/azure/members'
      fullPath: '/dashboard/azure/members'
      preLoaderRoute: typeof DashboardAzureMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/web/groups-by-label/': {
      id: '/dashboard/web/groups-by-label/'
      path: '/groups-by-label'
      fullPath: '/dashboard/web/groups-by-label/'
      preLoaderRoute: typeof DashboardWebGroupsByLabelIndexRouteImport
      parentRoute: typeof DashboardWebRoute
    }
    '/dashboard/telegram/users/': {
      id: '/dashboard/telegram/users/'
      path: '/telegram/users'
      fullPath: '/dashboard/telegram/users/'
      preLoaderRoute: typeof DashboardTelegramUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/web/tags/$tag': {
      id: '/dashboard/web/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/dashboard/web/tags/$tag'
      preLoaderRoute: typeof DashboardWebTagsTagRouteImport
      parentRoute: typeof DashboardWebRoute
    }
    '/dashboard/web/groups-by-label/$': {
      id: '/dashboard/web/groups-by-label/$'
      path: '/groups-by-label/$'
      fullPath: '/dashboard/web/groups-by-label/$'
      preLoaderRoute: typeof DashboardWebGroupsByLabelSplatRouteImport
      parentRoute: typeof DashboardWebRoute
    }
    '/dashboard/telegram/users/$userId': {
      id: '/dashboard/telegram/users/$userId'
      path: '/telegram/users/$userId'
      fullPath: '/dashboard/telegram/users/$userId'
      preLoaderRoute: typeof DashboardTelegramUsersUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardWebRouteChildren {
  DashboardWebAssociationsRoute: typeof DashboardWebAssociationsRoute
  DashboardWebFaqsRoute: typeof DashboardWebFaqsRoute
  DashboardWebGroupLabelsRoute: typeof DashboardWebGroupLabelsRoute
  DashboardWebGuidesRoute: typeof DashboardWebGuidesRoute
  DashboardWebProjectsRoute: typeof DashboardWebProjectsRoute
  DashboardWebGroupsByLabelSplatRoute: typeof DashboardWebGroupsByLabelSplatRoute
  DashboardWebTagsTagRoute: typeof DashboardWebTagsTagRoute
  DashboardWebGroupsByLabelIndexRoute: typeof DashboardWebGroupsByLabelIndexRoute
}

const DashboardWebRouteChildren: DashboardWebRouteChildren = {
  DashboardWebAssociationsRoute: DashboardWebAssociationsRoute,
  DashboardWebFaqsRoute: DashboardWebFaqsRoute,
  DashboardWebGroupLabelsRoute: DashboardWebGroupLabelsRoute,
  DashboardWebGuidesRoute: DashboardWebGuidesRoute,
  DashboardWebProjectsRoute: DashboardWebProjectsRoute,
  DashboardWebGroupsByLabelSplatRoute: DashboardWebGroupsByLabelSplatRoute,
  DashboardWebTagsTagRoute: DashboardWebTagsTagRoute,
  DashboardWebGroupsByLabelIndexRoute: DashboardWebGroupsByLabelIndexRoute,
}

const DashboardWebRouteWithChildren = DashboardWebRoute._addFileChildren(
  DashboardWebRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardWebRoute: typeof DashboardWebRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAzureMembersRoute: typeof DashboardAzureMembersRoute
  DashboardReportsGroupLinksRoute: typeof DashboardReportsGroupLinksRoute
  DashboardReportsResolvedRoute: typeof DashboardReportsResolvedRoute
  DashboardTelegramGrantsRoute: typeof DashboardTelegramGrantsRoute
  DashboardTelegramGroupsRoute: typeof DashboardTelegramGroupsRoute
  DashboardWhatsappGroupsRoute: typeof DashboardWhatsappGroupsRoute
  DashboardTelegramUsersUserIdRoute: typeof DashboardTelegramUsersUserIdRoute
  DashboardTelegramUsersIndexRoute: typeof DashboardTelegramUsersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardWebRoute: DashboardWebRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAzureMembersRoute: DashboardAzureMembersRoute,
  DashboardReportsGroupLinksRoute: DashboardReportsGroupLinksRoute,
  DashboardReportsResolvedRoute: DashboardReportsResolvedRoute,
  DashboardTelegramGrantsRoute: DashboardTelegramGrantsRoute,
  DashboardTelegramGroupsRoute: DashboardTelegramGroupsRoute,
  DashboardWhatsappGroupsRoute: DashboardWhatsappGroupsRoute,
  DashboardTelegramUsersUserIdRoute: DashboardTelegramUsersUserIdRoute,
  DashboardTelegramUsersIndexRoute: DashboardTelegramUsersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
